fix: handle promise rejections
Red-UI/packer pull request #5
Opened 2017-01-07 09:38 UTC by GiantMing

2017-01-07 12:23 UTC, wssgcg1213 requested changes
Request change

2017-01-07 12:23 UTC, wssgcg1213 commented on bin/init.js
> +      console.trace(e)
缩进是 2 space

2017-01-07 12:23 UTC, wssgcg1213 commented on bin/init.js
> +      console.trace(e)
应该用 err 或者 error 来表示

2017-01-07 15:29 UTC, GiantMing commented
改好了

2017-01-08 03:56 UTC, wssgcg1213 commented
plus 1

2017-01-08 13:23 UTC, merged